### ISSUE TITLE
3MF cannot be read / converted to STL

### ISSUE THREAD

**Issue by rpnfan** [Rookwork/Voyager-keywell-adapters#1]
Many services do only except STL files. The 3MF should be able to convert to STL, but all tools I tried gave an error message that the filetype is not correct (not 3MF)!? Any ideas how to fix that?

**Comment by Rookwork** [comment]
Interesting that 3mf isn't supported! Well, no problem. I just added the STL files for each adapter. Just be careful to double-check your quantities because there are several different files for each part of the board.

**Comment by rpnfan** [comment]
Thanks a lot, that is great! :-)

**Comment by OneGraund** [comment]
Hey, would be nice if you could also upload stl file for both halves :) so that people don't drag and drop 60 models in their god awful slicers (couldn't be me)
