### ISSUE TITLE
Moonlander

### ISSUE THREAD

**Issue by naudor** [Rookwork/Voyager-keywell-adapters#2]
Hi, can you explain how to adapt it to the Moonlander keyboard? Would a complete rework be necessary, or could it be done with just some adapters?

Thanks

**Comment by Rookwork** [comment]
Hi! It wouldn't really make sense to try to adapt these to a Moonlander — it would be better to make a new set of adapters to work with MX switches. That said, I wouldn't really recommend that either for a couple of reasons:

1. The Choc switches are short so they can tolerate a little extra height from these adapters without getting comically tall. The MX switches are already full-height, so adding even more height would get kind of silly. 
2. The incline of these adapters is not super extreme. You would get a similar effect from just using a sculpted set of keycaps, like the [official blank set](https://www.zsa.io/moonlander/accessories) for the Moonlander. 

Hope that helps!
